wip changes

diff --git a/src/tools/pm_apply b/src/tools/pm_apply
--- a/src/tools/pm_apply
+++ b/src/tools/pm_apply
@@ -5,21 +5,24 @@
 #
 
 # Root
-PM_VAR_DIR=/var/lib/patchmanager3
-PATCH_ROOT_DIR=/usr/share/patchmanager/patches
+PM_VAR_DIR="/var/lib/patchmanager3"
+PATCH_ROOT_DIR="/usr/share/patchmanager/patches"
 
 # Paths / Files
-PATCH_DIR=${PATCH_ROOT_DIR}/${1}
+PATCH_DIR="$PATCH_ROOT_DIR/$1"
 
-PM_LOG_FILE=${PM_VAR_DIR}/patchmanager.log
-PM_PATCH_BACKUP_ROOT_DIR=${PM_VAR_DIR}/patches
-PM_PATCH_BACKUP_DIR=${PM_PATCH_BACKUP_ROOT_DIR}/${1}
+PM_LOG_FILE="$PM_VAR_DIR/patchmanager.log"
+PM_PATCH_BACKUP_ROOT_DIR="$PM_VAR_DIR/patches"
+PM_PATCH_BACKUP_DIR="$PM_PATCH_BACKUP_ROOT_DIR/$1"
 
 # Constants
-PATCH_NAME=unified_diff.patch
+PATCH_NAME="unified_diff.patch"
+PATCH_PATH="$PATCH_DIR/$PATCH_NAME"
+
+ROOT_DIR="/tmp/patchmanager"
 
 # Applications
-PATCH_EXEC=/usr/bin/patch
+PATCH_EXEC="/usr/bin/patch"
 
 #
 # Here starts the part where all the magic happens
@@ -30,7 +33,7 @@ PATCH_EXEC=/usr/bin/patch
 #
 
 log() {
-  echo "$@" |& tee -a ${PM_LOG_FILE}
+  echo "$@" | tee -a "$PM_LOG_FILE"
 }
 
 failure() {
@@ -50,30 +53,30 @@ success() {
 }
 
 verify_text_patch() {
-  if [ -f ${PATCH_DIR}/${PATCH_NAME} ]; then
+  if [ -f "$PATCH_PATH" ]; then
     log
     log "----------------------------------"
     log "Dry running patch"
     log "----------------------------------"
     log
 
-    ${PATCH_EXEC} -p 1 -d /tmp/patchmanager --dry-run < ${PATCH_DIR}/${PATCH_NAME} |& tee -a ${PM_LOG_FILE}
+    $PATCH_EXEC -p 1 -d "$ROOT_DIR" --dry-run < "$PATCH_PATH" 2>&1 | tee -a "$PM_LOG_FILE" ; test ${PIPESTATUS[0]} -eq 0
 
-    if [ ${?} -ne 0 ]; then
+    if [ $? -ne 0 ]; then
       failure
     fi
   fi
 }
 
 install_text_patch() {
-  if [ -f ${PATCH_DIR}/${PATCH_NAME} ]; then
+  if [ -f "$PATCH_PATH" ]; then
     log
     log "----------------------------------"
     log "Applying text patch"
     log "----------------------------------"
     log
 
-    ${PATCH_EXEC} -p 1 -d /tmp/patchmanager --no-backup-if-mismatch < ${PATCH_DIR}/${PATCH_NAME} |& tee -a ${PM_LOG_FILE}
+    $PATCH_EXEC -p 1 -d "$ROOT_DIR" --no-backup-if-mismatch < "$PATCH_PATH" 2>&1 | tee -a "$PM_LOG_FILE" ; test ${PIPESTATUS[0]} -eq 0
   fi
 }
 
@@ -84,52 +87,52 @@ create_backup_patch() {
   log "----------------------------------"
   log
 
-  mkdir -p ${PM_PATCH_BACKUP_ROOT_DIR} > /dev/null 2>&1
-  cp -fr ${PATCH_DIR} ${PM_PATCH_BACKUP_DIR} > /dev/null 2>&1
+  mkdir -p "$PM_PATCH_BACKUP_ROOT_DIR" > /dev/null 2>&1
+  cp -f "$PATCH_DIR/$PATCH_NAME" "$PM_PATCH_BACKUP_DIR" > /dev/null 2>&1
   log "Created backup"
-  log "  backup: ${PM_PATCH_BACKUP_DIR}"
+  log "  backup: $PM_PATCH_BACKUP_DIR"
 }
 
 #
 # Bunch of safety checks and required initializations
 #
 
-mkdir -p ${PM_VAR_DIR} > /dev/null 2>&1
+mkdir -p "$PM_VAR_DIR" > /dev/null 2>&1
 
-if [ ! -f ${PM_LOG_FILE} ]; then
-  log "*** Patch Log Created by Install $(date) ***"
+if [ ! -f "$PM_LOG_FILE" ]; then
+  log "*** Patch Log Created by Apply $(date) ***"
 fi
 
 log
-log "------------------------------------------------------"
+log "----------------------------------"
 log "PM APPLY $(date)"
-log "------------------------------------------------------"
+log "----------------------------------"
 log
 
-log $(basename ${PATCH_DIR})
+log $(basename "$PATCH_DIR")
 
-if [ -f ${PATCH_DIR}/${PATCH_NAME} ]; then
+if [ -f "$PATCH_PATH" ]; then
   log "  contains text patch"
 fi
 
 log
 
-if [ ! -x ${PATCH_EXEC} ]; then
-  log "ERROR: Cannot find ${PATCH_EXEC}"
+if [ ! -x "$PATCH_EXEC" ]; then
+  log "ERROR: Cannot find $PATCH_EXEC"
   failure
 fi
 
-if [ -z ${PATCH_DIR} ]; then
+if [ -z "$PATCH_DIR" ]; then
   log "ERROR: PATCH_DIR must be given for installing"
   failure
 fi
 
-if [ ! -d ${PATCH_DIR} ]; then
-  log "ERROR: ${PATCH_DIR} is not a directory or does not exist!"
+if [ ! -d "$PATCH_DIR" ]; then
+  log "ERROR: $PATCH_DIR is not a directory or does not exist!"
   failure
 fi
 
-if [ ! -f ${PATCH_DIR}/${PATCH_NAME} ]; then
+if [ ! -f "$PATCH_PATH" ]; then
   log "ERROR: Cannot find patch file !"
   failure
 fi
diff --git a/src/tools/pm_unapply b/src/tools/pm_unapply
--- a/src/tools/pm_unapply
+++ b/src/tools/pm_unapply
@@ -5,21 +5,31 @@
 #
 
 # Root
-PM_VAR_DIR=/var/lib/patchmanager3
-PATCH_ROOT_DIR=/usr/share/patchmanager/patches
+PM_VAR_DIR="/var/lib/patchmanager3"
+PATCH_ROOT_DIR="/usr/share/patchmanager/patches"
 
 # Paths / Files
-PATCH_DIR=${PATCH_ROOT_DIR}/${1}
+PATCH_DIR="$PATCH_ROOT_DIR/$1"
 
-PM_LOG_FILE=${PM_VAR_DIR}/patchmanager.log
-PM_PATCH_BACKUP_ROOT_DIR=${PM_VAR_DIR}/patches
-PM_PATCH_BACKUP_DIR=${PM_PATCH_BACKUP_ROOT_DIR}/${1}
+PM_LOG_FILE="$PM_VAR_DIR/patchmanager.log"
+PM_PATCH_BACKUP_ROOT_DIR="$PM_VAR_DIR/patches"
+PM_PATCH_BACKUP_DIR="$PM_PATCH_BACKUP_ROOT_DIR/$1"
 
 # Constants
 PATCH_NAME=unified_diff.patch
+PATCH_PATH="$PATCH_DIR/$PATCH_NAME"
+PATCH_BACKUP="$PM_PATCH_BACKUP_DIR/$PATCH_NAME"
+
+ROOT_DIR="/tmp/patchmanager"
 
 # Applications
-PATCH_EXEC=/usr/bin/patch
+PATCH_EXEC="/usr/bin/patch"
+
+if [ -f "$PATCH_BACKUP" ]; then
+  PATCH_FILE="$PATCH_BACKUP"
+else
+  PATCH_FILE="$PATCH_PATH"
+fi
 
 #
 # Here starts the part where all the magic happens
@@ -30,7 +40,7 @@ PATCH_EXEC=/usr/bin/patch
 #
 
 log() {
-  echo "$@" |& tee -a ${PM_LOG_FILE}
+  echo "$@" 2>&1 | tee -a "$PM_LOG_FILE"
 }
 
 failure() {
@@ -49,36 +59,27 @@ success() {
   exit 0
 }
 
-find_patch_file() {
-  if [ -f ${PM_PATCH_BACKUP_DIR}/${PATCH_NAME} ]; then
-    patch_file=${PM_PATCH_BACKUP_DIR}/${PATCH_NAME}
-  else
-    patch_file=${PATCH_DIR}/${PATCH_NAME}
-  fi
-}
-
 verify_text_patch() {
-  if [ -f ${patch_file} ]; then
+  if [ -f "$PATCH_FILE" ]; then
     log
     log "----------------------------------"
     log "Dry running patch"
     log "----------------------------------"
     log
 
-    ${PATCH_EXEC} -R -p 1 -d /tmp/patchmanager --dry-run < ${patch_file} |& tee -a ${PM_LOG_FILE}
+    $PATCH_EXEC -R -p 1 -d "$ROOT_DIR" --dry-run < "$PATCH_FILE" 2>&1 | tee -a "$PM_LOG_FILE" ; test ${PIPESTATUS[0]} -eq 0
   fi
 }
 
 remove_text_patch() {
-  if [ -f ${patch_file} ]; then
-      log
-      log "----------------------------------"
-      log "Unapplying text patch"
-      log "----------------------------------"
-      log
+  if [ -f "$PATCH_FILE" ]; then
+    log
+    log "----------------------------------"
+    log "Unapplying text patch"
+    log "----------------------------------"
+    log
 
-      ${PATCH_EXEC} -R -p 1 -d /tmp/patchmanager --no-backup-if-mismatch < ${patch_file} |& tee -a ${PM_LOG_FILE}
-    fi
+    $PATCH_EXEC -R -p 1 -d "$ROOT_DIR" --no-backup-if-mismatch < "$PATCH_FILE" 2>&1 | tee -a "$PM_LOG_FILE" ; test ${PIPESTATUS[0]} -eq 0
   fi
 }
 
@@ -89,43 +90,39 @@ clean_backup_patch() {
   log "----------------------------------"
   log
 
-  rm -fr ${PM_PATCH_BACKUP_DIR} > /dev/null 2>&1
+  rm -f "$PM_PATCH_BACKUP_DIR" > /dev/null 2>&1
   log "Removed backup"
-  log "  backup: ${PM_PATCH_BACKUP_DIR}"
+  log "  backup: $PM_PATCH_BACKUP_DIR"
 }
 
 #
 # Bunch of safety checks and required initializations
 #
 
-if [ ! -f ${PM_LOG_FILE} ]; then
-  log "*** Patch Log Created by Remove $(date) ***"
+if [ ! -f "$PM_LOG_FILE" ]; then
+  log "*** Patch Log Created by Unapply $(date) ***"
 fi
 
-find_patch_file
-
-# mount -o rw,remount / | tee -a ${PM_LOG_FILE} 1>&2
-
 log
-log "------------------------------------------------------"
+log "----------------------------------"
 log "PM UNAPPLY $(date)"
-log "------------------------------------------------------"
+log "----------------------------------"
 log
 
-log $(basename ${PATCH_DIR})
+log $(basename "$PATCH_DIR")
 
-if [ -f ${patch_file} ]; then
+if [ -f "$PATCH_FILE" ]; then
   log "  contains text patch"
 fi
 
 log
 
-if [ ! -x ${PATCH_EXEC} ]; then
-  log "ERROR: Cannot find ${PATCH_EXEC}"
+if [ ! -x "$PATCH_EXEC" ]; then
+  log "ERROR: Cannot find $PATCH_EXEC"
   failure
 fi
 
-if [ ! -f ${patch_file} ]; then
+if [ ! -f "$PATCH_FILE" ]; then
   log "ERROR: Cannot find patch file !"
   failure
 fi
